FEAT: Display Work Companies, Educational Institutions In User Modal
Sultannis/ii-platform-client pull request #11
Opened 2023-01-28 22:58 UTC by Mukhaman

Work companies and educational institutions data is displayed on modal of user when clicked

2023-01-29 21:10 UTC, Sultannis commented on src/api/dao/WorkCompany.dao.ts
> +    end_date: string;
Так как end_date опциональный параметр, ему и всем другим опциональным параметрам нужно проставлять ? перед :  . 

end_date: string;   -> end_date?: string

2023-01-29 21:10 UTC, Sultannis commented on src/api/repositories/contact-lists.repository.ts
> +export const fetchPersonContactList = (personId: number) =>
В typescript'е мы так же можем указывать тип данных который возавращает функция

5'ая строка будет выглядеть так:
export const fetchPersonContactList = (personId: number): **Promise\<ContactList\>** => 

конечно же с импортированым entity ContactList

2023-01-29 21:10 UTC, Sultannis commented on src/api/repositories/contact-lists.repository.ts
> +export const fetchPersonContactList = (personId: number) =>
Необходимо типизировать все функции в существующих репозиториях

2023-01-29 21:10 UTC, Sultannis commented on src/common/components/CommonPersonModal/CommonPersonModal.vue
> +            <PersonProjectsPage v-if="seleсtedLinkTitle == 'Проекты'" />
Так как мы решили перевести платформу на англ и ты работаешь с компонентом модалки давай начнем переводить подобные элементы

2023-01-29 21:10 UTC, Sultannis commented on src/common/components/CommonPersonModal/CommonPersonModal.vue
> +            <PersonEducationPage v-if="seleсtedLinkTitle == 'Educational Institutions'"/>
Educational Institution слишком длинный заголовок. Education будет достаточно.

2023-01-29 21:10 UTC, Sultannis commented on src/common/components/CommonPersonModal/CommonPersonModal.vue
> +  position: relative;
Зачем тут postion: relative. Если ты хочешь абсолютно позиционировать иконку значение параметра должно быть absolute, но стоит избегать абсолютного позиционирования. В данном случае достаточно прописать margin-top: 5px

2023-01-29 21:10 UTC, Sultannis commented on src/common/components/CommonProfileImageUpload/CommonProfileImageUpload.vue
> +const { person, personFetchLoading, fetchPerson } = useFetchPerson();
Тут помимо person две пременные не используются, нужно убрать

2023-01-29 21:10 UTC, Sultannis commented on src/common/components/CommonProfileImageUpload/CommonProfileImageUpload.vue
> +const { person, personFetchLoading, fetchPerson } = useFetchPerson();
В целом получение url аватара пользователя в данном случае должно бытть реализовано через пропсы. Данный компонент переиспользуем, он не должен знать про существование person, иначе ты создаешь зависимость.

2023-01-29 21:10 UTC, Sultannis commented on src/common/components/PersonCommonPage/PersonCommonPage.vue
>        <div class="common__title">Контакты</div>
Стоит добавить скелетон загрузки для блока контактов

2023-01-29 21:10 UTC, Sultannis commented on src/common/components/PersonCommonPage/PersonCommonPage.vue
> +        <i class='bx bxl-github common__icon' /> {{ contactList.githubLink }}
Необходимо поменять дивы с ссылками, на реальные элементы <a>  и добавить им параметр target="_blank".

2023-01-29 21:10 UTC, Sultannis commented on src/common/components/PersonCommonPage/PersonCommonPage.vue
> +        <i class='bx bxs-envelope common__icon' /> {{ contactList.email }}
Многие ссыки на контакты опциональны, нужно их скрывать если у пользователя отсутствует та или иная ссылка

2023-01-29 21:10 UTC, Sultannis commented on src/common/components/PersonEducationPage/PersonEducationPage.vue
> +
Пустую строку можно убрать

2023-01-29 21:10 UTC, Sultannis commented on src/common/components/PersonEducationPage/PersonEducationPage.vue
> +            </div>
Размер скелетонов не соответсвует размерам реальных карточек. Будет достаточно одного description-skeleton

2023-01-29 21:10 UTC, Sultannis commented on src/common/components/PersonEducationPage/PersonEducationPage.vue
> +    <div class="institutions" v-if="!educationalInstitutionsLoading">
В компоненте переиспользуется div с классом institutions. Будет правильней прописать один div, внутри воспользоватся template элементами для условного рендеринга. Учти что v-if и v-for нельзя прописывать в одном элементе.

2023-01-29 21:10 UTC, Sultannis commented on src/common/components/PersonEducationPage/PersonEducationPage.vue
> +    />
По поводу форматирования, если у тебя не установлен prettier, его нужно установить. Я прописал config file для prettier, он должен подхватить конфигурацию сам. Так же не забудь проставить авто-форматирование на сохранение в vs code'е

2023-01-29 21:10 UTC, Sultannis commented on src/common/components/PersonEducationPage/components/EducationalInstitutionCard.vue
> +    reqauired: true,
Опечатка

2023-01-29 21:10 UTC, Sultannis commented on src/common/components/PersonEducationPage/components/EducationalInstitutionCard.vue
> +.institutions__item {
BEM подразумевает что у тебя присутствует base class от которого ты создаешь дочерние классы через "__" . Тут достаточно назвать класс institution, institution __title и тд.

2023-01-29 21:10 UTC, Sultannis commented on src/common/components/PersonProjectsPage/components/WorkCompanyCard.vue
> +  <div class="projects__item">
Коммент про нейминг класса распространяется и на этот компонент

2023-01-29 21:10 UTC, Sultannis commented on src/common/composables/fetchContactList.ts
> +
Пустую строку стоит убрать

2023-01-29 21:10 UTC, Sultannis commented on src/common/composables/fetchContactList.ts
> +
Пустую строку стоит убрать

2023-01-29 21:10 UTC, Sultannis commented on src/common/composables/fetchContactList.ts
> +
Пустую строку стоит убрать

2023-01-29 21:10 UTC, Sultannis commented on src/common/composables/fetchPerson.ts
> -      );
Для чего данный обработчик был удален? Нужно вернуть.

2023-01-31 12:47 UTC, Mukhaman commented on src/api/dao/WorkCompany.dao.ts
> +    end_date: string;
done

2023-01-31 12:54 UTC, Mukhaman commented on src/api/repositories/contact-lists.repository.ts
> +export const fetchPersonContactList = (personId: number) =>
done

2023-01-31 13:33 UTC, Mukhaman commented on src/common/components/CommonPersonModal/CommonPersonModal.vue
> +            <PersonProjectsPage v-if="seleсtedLinkTitle == 'Проекты'" />
done

2023-01-31 13:33 UTC, Mukhaman commented on src/common/components/CommonPersonModal/CommonPersonModal.vue
> +            <PersonEducationPage v-if="seleсtedLinkTitle == 'Educational Institutions'"/>
done

2023-01-31 13:34 UTC, Mukhaman commented on src/common/components/CommonPersonModal/CommonPersonModal.vue
> +  position: relative;
done

2023-01-31 13:57 UTC, Mukhaman commented on src/common/components/PersonProjectsPage/components/WorkCompanyCard.vue
> +  <div class="projects__item">
done

2023-01-31 13:58 UTC, Mukhaman commented on src/common/composables/fetchContactList.ts
> +
done

2023-01-31 13:58 UTC, Mukhaman commented on src/common/composables/fetchContactList.ts
> +
done

2023-01-31 13:58 UTC, Mukhaman commented on src/common/composables/fetchContactList.ts
> +
done

2023-01-31 14:12 UTC, Mukhaman commented on src/common/composables/fetchPerson.ts
> -      );
done

2023-01-31 14:15 UTC, Mukhaman commented on src/common/components/PersonEducationPage/components/EducationalInstitutionCard.vue
> +.institutions__item {
done

2023-01-31 14:15 UTC, Mukhaman commented on src/common/components/PersonEducationPage/components/EducationalInstitutionCard.vue
> +    reqauired: true,
done

2023-01-31 14:43 UTC, Mukhaman commented on src/common/components/CommonProfileImageUpload/CommonProfileImageUpload.vue
> +const { person, personFetchLoading, fetchPerson } = useFetchPerson();
done

2023-01-31 14:46 UTC, Mukhaman commented on src/common/components/PersonEducationPage/PersonEducationPage.vue
> +
done

2023-01-31 15:20 UTC, Mukhaman commented on src/common/components/PersonCommonPage/PersonCommonPage.vue
> +        <i class='bx bxl-github common__icon' /> {{ contactList.githubLink }}
done

2023-01-31 21:28 UTC, Mukhaman commented on src/common/components/PersonCommonPage/PersonCommonPage.vue
>        <div class="common__title">Контакты</div>
done

2023-01-31 21:29 UTC, Mukhaman commented on src/common/components/PersonEducationPage/PersonEducationPage.vue
> +            </div>
done

2023-01-31 21:43 UTC, Mukhaman commented on src/common/components/PersonEducationPage/PersonEducationPage.vue
> +    <div class="institutions" v-if="!educationalInstitutionsLoading">
done

2023-02-01 23:58 UTC, Sultannis commented on src/api/dao/WorkCompany.dao.ts
> +    end_date: string;
Хорошо ты типизировал DAO файлы. Теперь если ты откроешь соответствующие mapper'ы ты увидишь ошибки, появляются они из-за того что DAO и Entity файлы не соответсвуют друг другу, нужно так же обновить Entity файлы

2023-02-02 00:11 UTC, Sultannis commented on src/api/repositories/contact-lists.repository.ts
> +export const fetchPersonContactList = (personId: number) =>
Не все репозитории типизированы

2023-02-02 00:13 UTC, Sultannis commented on src/common/components/CommonProfileImageUpload/CommonProfileImageUpload.vue
> +const { person, personFetchLoading, fetchPerson } = useFetchPerson();
Второй комментарии не имплементирован.

2023-02-02 00:18 UTC, Sultannis commented on src/common/components/PersonCommonPage/PersonCommonPage.vue
> +        <i class='bx bxl-github common__icon' /> {{ contactList.githubLink }}
В чем был смысл менять дивы на ссылки если они не кликабельны? Нужно прописать href атрибут.

2023-02-02 12:17 UTC, Mukhaman commented on src/common/components/CommonProfileImageUpload/CommonProfileImageUpload.vue
> +const { person, personFetchLoading, fetchPerson } = useFetchPerson();
done

2023-02-02 12:57 UTC, Mukhaman commented on src/common/components/PersonCommonPage/PersonCommonPage.vue
> +        <i class='bx bxl-github common__icon' /> {{ contactList.githubLink }}
done

2023-02-02 13:14 UTC, Mukhaman commented on src/api/dao/WorkCompany.dao.ts
> +    end_date: string;
done

2023-02-02 13:17 UTC, Mukhaman commented on src/api/repositories/contact-lists.repository.ts
> +export const fetchPersonContactList = (personId: number) =>
done

2023-02-02 16:09 UTC, Mukhaman commented on src/common/components/PersonCommonPage/PersonCommonPage.vue
> +        <i class='bx bxs-envelope common__icon' /> {{ contactList.email }}
done

2023-02-02 16:47 UTC, Sultannis commented on src/common/components/CommonProfileImageUpload/CommonProfileImageUpload.vue
> +const { person, personFetchLoading, fetchPerson } = useFetchPerson();
Имплементация данного компонента подразумевает что мы можем загрузить картинку, я проморгал этот момент. Так как в данном модальном окне мы видим данные других пользователей, мы не должны позвлять загружать картинку. Нужно создать отдельный компонент в котором присутствует лишь отображение аватара либо дефолтной картинки. Данный компонент стоит оставить, им мы воспользуемся в модалке User'а

2023-02-02 16:52 UTC, Sultannis commented
Необходимо создать компоненты отображающие что у пользователя нет educational-institutions или work-companies.

2023-02-02 19:48 UTC, Mukhaman commented on src/common/components/CommonProfileImageUpload/CommonProfileImageUpload.vue
> +const { person, personFetchLoading, fetchPerson } = useFetchPerson();
done

2023-02-02 21:06 UTC, Sultannis requested changes

2023-02-02 21:06 UTC, Sultannis commented on src/common/components/CommonPersonModal/CommonPersonModal.vue
> +            />
Повторяющихся компонентов нужно избегать. Здесь лучше реализовать следующую логику. 
 - Во-первых, вместо того чтобы через url ссылаться на какой-то турецкий сайт, (откуда ты его нашел вообще?) лучше скачать эту png картинку и хранить ее в ассетах. Так мы будем моментально рендерить дефолт, а ссылатся на него через относительный путь.
 - Во-вторых, нужно создать computed property который будет обрабатывать какой путь отдавать сейчас и передавать его в компонент Image
 - В-третьих, присутствует edge case когда не смотря на то что person.avatarUrl присутствует, сам путь или файл 
 может быть сломан. Для таких случаев у элемента \<img\> присутствует ивент error. Его можно обработать через @error. Я бы добавил watcher в CommonPersonModal который смотрит на person.avatarUrl и присваевает его значение в локальную переменную. От этой переменной мы можем создать вышеупомянутый computed property. В случае когда img выкинул error, компонент CommonProfileImage должен emit'ить собственный ивент который будет присваевать локальной переменной CommonPersonModal значение null. Тем самым computed property будет обновлятся на дефолт.

2023-02-02 21:06 UTC, Sultannis commented on src/common/components/PersonEducationPage/PersonEducationPage.vue
> +      />
На двух страницах данный компонент выглядит неуклюже. Нужно через пропсы создать определенную кастомизацию компонента, добавить кастомную высоту, описание... Пример есть в компоненте CommonLoadingBlock

2023-02-25 18:15 UTC, merged